# CONEXAO LOCAL (H2 DATABASE EM MEMORIA)
spring.datasource.url=jdbc:h2:mem:escolati;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# CONEXAO SUPABASE (POSTGRESQL) - Descomente para voltar a usar na nuvem
# spring.datasource.url=jdbc:postgresql://db.yrbemlwmmyeqfwzjaksr.supabase.co:5432/postgres?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
# spring.datasource.username=postgres
# spring.datasource.password=SUA_SENHA_DO_SUPABASE_AQUI
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect